version: '3.7'

services:
  currency-exchange:
    image: christine0228/mmv2-currency-exchange-service:0.0.1-SNAPSHOT
    mem_limit: 1G
    ports: 
      - "8000:8000"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
        EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/eureka

  naming-server:
    image: christine0228/mmv2-naming-server:0.0.1-SNAPSHOT
    mem_limit: 1G
    ports: 
      - "8761:8761"
    networks:
      - currency-network



networks:
  currency-network: