server:
  port: 8090

spring:
  application:
    name: car-service
#  datasource:
#    url: jdbc:mysql://localhost:3306/springcloud?serverTimezone=GMT%2B8&characterEncoding=utf-8&useUnicode=true
#    username: root
#    password: 123456789
#    driverClassName: com.mysql.cj.jdbc.Driver
#  jpa:
#      hibernate:
#        ddl-auto: update
#      show-sql: true 


