spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: file://Users/christinehsieh/Documents/UdemySpringCloudPractice/udemySpringCloudConfigGit
         
server:
  port: 8888
